name: vibe_design
description: "Vibe Design - Твій шлях у design починається тут"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: 3.29.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # ui
  flutter_svg: ^2.0.17
  flutter_gen: ^5.8.0
  smooth_page_indicator: ^1.2.1

  # crashlytics
  sentry_flutter: ^8.0.0

  # architecture
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  injectable: ^2.3.2
  go_router: ^14.0.0
  formz: ^0.7.0
  collection: ^1.18.0

  # localization
  easy_localization: ^3.0.6

  # network & storage
  url_launcher: ^6.3.1
  fetch_client: ^1.0.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.1.5
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icons/favicon.png"


flutter_gen:
  output: lib/gen/
  assets:
    exclude:
      - assets/translations/**
  fonts:
    enabled: true
    outputs:
      class_name: AppFontsFamily

  integrations:
    flutter_svg: true
  colors:
      enabled: true
      inputs:
        - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900