name: vibe_design
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: 3.27.1

dependencies:
  flutter:
    sdk: flutter

  # ui
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

  # crashlytics
  sentry_flutter: ^8.0.0

  # architecture
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  injectable: ^2.3.2
  go_router: ^14.0.0
  formz: ^0.7.0
  collection: ^1.18.0

  # localization
  easy_localization: ^3.0.6

  # network & storage
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.1.5
  #flutter_launcher_icons: ^0.13.1


# flutter_launcher_icons:
#  web:
#    generate: true
#    image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/translations/